runtime: nodejs8
service: default
env_variables:
        PORT: 80
handlers:
        - url: /
          static_files: dist/koth-passwordistaco/index.html
          upload: dist/koth-passwordistaco/index.html
    
        - url: /
          static_dir: dist/koth-passwordistaco
